name: Build and Deploy

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  issues: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install theme
        run: |
          if [ ! -d "themes/halcyon" ]; then
            git clone https://github.com/m0ddr/halcyon themes/halcyon
          fi
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.1
      - uses: actions/configure-pages@v4
      - run: zola build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment

  link-check:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install link-sweep
      
      - name: Run link-sweep
        id: check
        run: |
          if link-sweep --timeout 10 > results.txt 2>&1; then
            echo "status=pass" >> $GITHUB_OUTPUT
          else
            echo "status=fail" >> $GITHUB_OUTPUT
          fi

      - name: Manage issues
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const results = fs.readFileSync('results.txt', 'utf8');
            const status = '${{ steps.check.outputs.status }}';
            
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['broken-links'],
              state: 'open'
            });

            if (status === 'pass') {
              for (const issue of issues.data) {
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed'
                });
              }
            } else {
              const body = `# Link Check Results\nDate: ${new Date().toISOString()}\n\n\`\`\`\n${results}\n\`\`\``;
              
              if (issues.data.length > 0) {
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issues.data[0].number,
                  body: body
                });
              } else {
                await github.rest.issues.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: '🔗 Broken Links Detected',
                  body: body,
                  labels: ['broken-links']
                });
              }
            }
